# Generated by Django 5.2.6 on 2025-09-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price Per Hour')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
