# Generated by Django 5.2.6 on 2025-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('type', models.CharField(choices=[('football', 'Football'), ('tennis', 'Tennis'), ('basketball', 'Basketball')], max_length=20, verbose_name='Sport Type')),
                ('price_per_session', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price per Session (ETB)')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['type', 'is_active'], name='field_field_type_335227_idx')],
            },
        ),
    ]
