# Generated by Django 5.1.3 on 2025-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fields/', verbose_name='Image'),
        ),
    ]
