# Generated by Django 5.1.3 on 2025-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
