# Generated by Django 5.2.6 on 2025-09-19 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.IntegerField(default=1, verbose_name='Duration')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Paid')),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Playground')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslot.timeslot', verbose_name='Time Slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
