# Generated by Django 5.2.6 on 2025-09-19 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('field', '0001_initial'),
        ('timeslot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='field.field'),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingseries',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='timeslot.timeslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.bookingseries'),
        ),
        migrations.AddField(
            model_name='chapapayment',
            name='series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.bookingseries'),
        ),
        migrations.AddField(
            model_name='fieldblackout',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='field.field'),
        ),
        migrations.AddField(
            model_name='fieldblackout',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeslot.timeslot'),
        ),
        migrations.AddField(
            model_name='fieldweeklyslot',
            name='playground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='field.field'),
        ),
        migrations.AddField(
            model_name='fieldweeklyslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeslot.timeslot'),
        ),
        migrations.AddIndex(
            model_name='bookingseries',
            index=models.Index(fields=['status'], name='booking_boo_status_a9e280_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingseries',
            index=models.Index(fields=['playground', 'weekday'], name='booking_boo_playgro_995f13_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingseries',
            index=models.Index(fields=['created_at'], name='booking_boo_created_bdfe04_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='booking_boo_date_f02e27_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['playground', 'date'], name='booking_boo_playgro_568813_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('playground', 'date', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='chapapayment',
            index=models.Index(fields=['status'], name='booking_cha_status_478dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='chapapayment',
            index=models.Index(fields=['created_at'], name='booking_cha_created_ef45e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldblackout',
            index=models.Index(fields=['playground', 'date'], name='booking_fie_playgro_d4c85e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldblackout',
            unique_together={('playground', 'date', 'time_slot')},
        ),
        migrations.AddIndex(
            model_name='fieldweeklyslot',
            index=models.Index(fields=['playground', 'day_of_week'], name='booking_fie_playgro_c45b23_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldweeklyslot',
            index=models.Index(fields=['is_open'], name='booking_fie_is_open_540307_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fieldweeklyslot',
            unique_together={('playground', 'day_of_week', 'time_slot')},
        ),
    ]
