# Generated by Django 5.1.3 on 2025-09-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Duration'),
        ),
    ]
