# Generated by Django 5.1.3 on 2025-09-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('field', '0001_initial'),
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('playground', 'date', 'time_slot')},
        ),
    ]
