# Generated by Django 5.1.3 on 2025-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Paid'),
        ),
    ]
