# Generated by Django 5.1.3 on 2025-09-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is Booked'),
        ),
    ]
