# Generated by Django 5.1.3 on 2025-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=50, null=True, verbose_name='Role'),
        ),
    ]
