# Generated by Django 5.2.6 on 2025-09-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
