# Generated by Django 5.1.3 on 2025-09-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
    ]
