# Generated by Django 5.1.3 on 2025-09-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscribers_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'ordering': ['-created_at']},
        ),
    ]
