# Generated by Django 5.2.6 on 2025-09-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time', 'end_time'],
                'constraints': [models.UniqueConstraint(fields=('start_time', 'end_time'), name='uniq_timeslot_start_end')],
            },
        ),
    ]
