# Generated by Django 5.1.3 on 2025-09-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Booked'),
        ),
    ]
