# Generated by Django 5.1.3 on 2025-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time', 'end_time']},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='price_per_hour',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='status',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('start_time', 'end_time'), name='uniq_timeslot_start_end'),
        ),
    ]
