# Generated by Django 5.1.3 on 2025-09-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_field_image'),
        ('timeslot', '0002_remove_timeslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Field'),
        ),
    ]
